module.exports = {
  AmazonAdapter:    require('./amazon'),
  FlipkartAdapter:  require('./flipkart'),
  MeeshoAdapter:    require('./meesho'),
  MyntraAdapter:    require('./myntra'),
  NykaaAdapter:     require('./nykaa'),
  AjioAdapter:      require('./ajio'),
  TataCliqAdapter:  require('./tata-cliq'),
  SnapdealAdapter:  require('./snapdeal'),
  GlowRoadAdapter:  require('./glowroad'),
  JioMartAdapter:   require('./jiomart'),
  PaytmMallAdapter: require('./paytm-mall'),
  LimeRoadAdapter:  require('./limeroad'),
  EbayAdapter:      require('./ebay'),
  EtsyAdapter:      require('./etsy'),
  WalmartAdapter:   require('./walmart'),
  LazadaAdapter:    require('./lazada'),
  ShopeeAdapter:    require('./shopee'),
  NoonAdapter:         require('./noon'),
  MercadoLibreAdapter: require('./mercado-libre'),
  AllegroAdapter:      require('./allegro'),
  FruugoAdapter:       require('./fruugo'),
  OnBuyAdapter:        require('./onbuy'),
  ManoManoAdapter:     require('./manomano'),
  RakutenAdapter:      require('./rakuten'),
  ZalandoAdapter:      require('./zalando'),
  KauflandAdapter:     require('./kaufland'),
  WishAdapter:         require('./wish'),
  ...require('./pending'),
};
